# -*- coding: utf-8 -*-
"""hash作業

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12W4RoR1LP9XCxe134CbdFTGUZE43AqL_
"""

with open('hw2_data.txt',mode='r') as fd: #with/as可以在處理完後自行關閉close()檔案，更方便。 r是開啟唯讀檔案的模式
  line = fd.readlines()       #檔案.readlines()可以讀取檔案的每一行，將每一行內容轉換成串列的一個項目
my_dict = {}               #readlines的s要小心不要忘記，readline會變成讀取一行中幾個字母
for i in range(0,len(line)):
  sure = int(my_dict.get(line[i].strip(),0))  #字串.strip()就可以去除字串前後空白或換行符號，以免有無換行符號被認定為不同key                                              
  if sure == 0:              #dictionary.get(key,回傳值)可以獲取key對應的value， 
    my_dict[line[i].strip()] = 1     #若沒有這個key(這裡是line[i])，就回傳我設定的回傳值(這裡我設定為0)
  elif sure != 0:             #若字典裡沒有該key，就加入，已經有了，對應數字就加一
    my_dict[line[i].strip()]+= 1
  else:
    print('error')
print('不重複的英文字有'+str(len(my_dict))+'個') #有幾個不重複的英文字
for word in sorted(my_dict):    #不重複的英文字分別有幾個
  times = my_dict[word]
  print('{}出現{}次'.format(word,times))
